 name: Revanced Patcher
 on:
  workflow_dispatch:
    inputs:
      REVANCED_URL:
        description: 'Give URL Link to correct youtube apk'
        required: true
        default: ''
      PROJECT_URL: 
        description: 'Give releases link to revanced project jar file'
        required: true
        default: 'https://github.com/revanced/revanced-cli/releases/download/v2.21.2/revanced-cli-2.21.2-all.jar'
      PATCHES_URL:
        description: 'Give releases link to revanced-patches jar file'
        required: true
        default: 'https://github.com/revanced/revanced-patches/releases/download/v2.175.0-dev.2/revanced-patches-2.175.0-dev.2.jar'
 jobs:
    build:
       runs-on: ubuntu-latest
       permissions:
          contents: write
       steps:
        - name: Display Run Parameters
          run: |
            echo "::group::User Environment Variables"
            echo "REVANCED_URL: ${{ github.event.inputs.REVANCED_URL }}"
            echo "PROJECT_URL: ${{ github.event.inputs.PROJECT_URL }}"
            echo "PROJECT_URL: ${{ github.event.inputs.PATCHES_URL }}"
        - name: Check Out
          uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
#        - name: Cleanup
#          uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
        - name: Prepare the environment
          run: |
            sudo apt update
             sudo apt-get install openjdk-11-jdk
        - name: Get Repo for Revanced Patcher
          run: |
           mkdir /home/runner/repo
           wget ${{ github.event.inputs.PROJECT_URL }} --directory-prefix=/home/runner/repo
     #    git clone ${{ github.event.inputs.PROJECT_URL }} ~/repo
        - name: Get Patches for Revanced Patcher
          run: |
            mkdir /home/runner/patches
            wget ${{ github.event.inputs.PATCHES_URL }} --directory-prefix=/home/runner/patches
        - name: Get APK
          run: |
            mkdir /home/runner/input
            wget ${{ github.event.inputs.REVANCED_URL }} --directory-prefix=/home/runner/input
        - name: Run Patch Script
          run: |
           chmod +x scripts/script.sh
           ./scripts/script.sh
        - name: Upload to Release
          uses: xresloader/upload-to-github-release@v1
          with: 
            file: "/home/runner/output/*.apk"
            name: ${{ github.run_id }}
            tag_name: ${{ github.run_id }}
            draft: true
          env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
