 name: Revanced Patcher

 on:
  workflow_dispatch:
    inputs:
      REVANCED_URL:
        description: 'Give URL Link to correct youtube apk'
        required: true
        default: ''
      PROJECT_URL: 
        description: 'Give git link to preferred revanced project'
        required: true
        default: 'https://github.com/NoName-exe/revanced-extended'
      
  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
       content: write
      steps: 
      - name: Display Run Parameters
        run: |
          echo "::group::User Environment Variables"
          echo "REVANCED_URL: ${{ github.event.inputs.REVANCED_URL }}"
          echo "PROJECT_URL: ${{ github.event.inputs.PROJECT_URL }}"
      - name: Check Out
         uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
      - name: Prepare the environment
        run: |
          sudo apt update
      - name: Run Patch Script
      
