 name: Revanced Patcher

 on:
  workflow_dispatch:
    inputs:
      REVANCED_URL:
        description: 'Give URL Link to correct youtube apk'
        required: true
        default: ''
      PROJECT_URL: 
        description: 'Give git link to revanced project jar'
        required: true
        default: 'https://github.com/revanced/revanced-cli/releases/download/v2.21.2/revanced-cli-2.21.2-all.jar'
      
  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
       content: write
      steps: 
      - name: Display Run Parameters
        run: |
          echo "::group::User Environment Variables"
          echo "REVANCED_URL: ${{ github.event.inputs.REVANCED_URL }}"
          echo "PROJECT_URL: ${{ github.event.inputs.PROJECT_URL }}"
      - name: Check Out
         uses: actions/checkout@v3
    # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - name: Cleanup
         uses: rokibhasansagar/slimhub_actions@main
      # That's it! Now use your normal steps
      - name: Prepare the environment
        run: |
          sudo apt update
      - name: Get Repo for Revanced Patcher
        run: |
         mkdir ~/repo
         wget ${{ github.event.inputs.PROJECT_URL }} ~/repo
     #    git clone ${{ github.event.inputs.PROJECT_URL }} ~/repo
         
      - name: Run Patch Script
        run: |
         chmod +x ./.github/scripts/script.sh
         ./.github/scripts/
      
